version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: 123456789
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mesages

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: mesages
    ports:
      - "3306:3306"
